- name: Staging Deployment Playbook
  hosts: stg_servers

  tasks:
  - name: Create Remote folder
    file:
      path: "{{ project_path }}"
      state: directory
    become: yes
    tags:
    - folder

  - name: Copying code
    ansible.posix.synchronize:
      src: ../../../
      dest: "{{ project_path }}"
      times: no
      recursive: yes
      rsync_path: "sudo -S -u {{ ansible_ssh_user }} rsync"
      rsync_opts:
      - "--exclude=node_modules"
      - "--exclude=infra"
      - "--exclude=.git"
    become: yes 
    tags:
    - copy

  - name: Restarting Processes
    ansible.builtin.command:
      cmd: "{{ restart_command }}"
      chdir: "{{ project_path }}"
    become: yes
    tags:
    - restart

# ansible-playbook stg_deploy_playbook.yml -i ./inventory/hosts.yml
